version: '3.1'

services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: yang@jhyang.xyz
      PGADMIN_DEFAULT_PASSWORD: jhyang
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80